# Generated by Django 5.2.4 on 2026-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulesControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_module",
                    models.CharField(
                        choices=[], help_text="Select the tool/module", max_length=100
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of uses allowed per day"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="The user group this limit applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_controls",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modules Control",
                "verbose_name_plural": "Modules Controls",
                "unique_together": {("name_of_module", "role")},
            },
        ),
    ]
