# Generated by Django 5.2.4 on 2026-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_usermoduleusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulescontrol",
            name="name_of_module",
            field=models.CharField(
                choices=[
                    ("career_planner", "Career Planner"),
                    ("mental_health_analyzer", "Mental Health Analyzer"),
                    ("news_portal", "News Portal"),
                    ("notes_assistant", "Notes Assistant"),
                    ("quiz_maker", "Quiz Maker"),
                    ("rate_limiter", "Rate Limiter"),
                    ("research_agent", "Research Agent"),
                    ("resume_scanner", "Resume Scanner"),
                    ("roadmap_creator", "Roadmap Creator"),
                ],
                help_text="Select the tool/module",
                max_length=100,
            ),
        ),
    ]
