# Generated by Django 5.2.4 on 2026-03-26 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_modulescontrol_name_of_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="career",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="year",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="career_goals",
            field=models.TextField(
                blank=True,
                help_text="What is your ultimate career objective?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Student", "Student"),
                    ("Professional", "Working Professional"),
                    ("Job Seeker", "Seeking Opportunities"),
                    ("Freelancer", "Freelancer"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="degree_name",
            field=models.CharField(
                blank=True,
                help_text="e.g., B.Tech in Computer Science",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("High School", "High School"),
                    ("Diploma", "Diploma"),
                    ("Bachelors", "Bachelors Degree"),
                    ("Masters", "Masters Degree"),
                    ("PhD", "PhD / Doctorate"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="portfolio_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_domain",
            field=models.CharField(
                blank=True,
                help_text="e.g., Software Engineering, Data Science, Marketing",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of skills (e.g., Python, SQL, Project Management)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
